Ornaments as indicators of Social change before and after European contact at Kiwulan, Northeastern Taiwan

Liying Wang
Ben Marwick

```{r}
library(ggplot2)
ggplot(iris, 
       aes(Sepal.Width, 
           Sepal.Length)) +
  geom_point()
```



Introduction and Research Question
 
Body ornaments are usually viewed as materials that convey social meaning or representations in a culture through the body as the scene to display (Joyce 2005). Foreign ornaments including glass beads, agate or carnelian beads, and metal objects first appear in Taiwan around 1,800 years ago through regional trade network in Southeast Asia (Wang and Liu 2007). Those new types of ornaments gradually replaced the earlier jade ornamental system in Taiwan during the Metal Age and reached a high peak of quantity and variety in the early 17th century when the Europeans arrived and involved the island in an international trade network on a large scale. Foreign trade goods introduced into the local indigenous societies in an European colonial or imperial contexts usually had an impact on local culture and societies in many parts of the world that usually involved in the transformation of indigenous economic, cultural, and socio-political systems (Dietler 1997; Junker 1993; Mitchell 2000; Silliman 2005). Contrary to as passive receptors of imperial power, the agency of indigenous people in the colonial contexts has been broadly discussed that stress active adoptions of foreign materials, negotiation between colonized and colonizer, and resistance of indigenous people through daily cultural practices (Given 2004; Mullins 2011; Silliman 2001; Rubertone 2000; Torrence 2000; Torrence and Clarke 2000; Voss 2005). 


Compared to other places in Asia and Oceania, the impact of European colonialism on indigenous communities in East Asia appears to have been much less pronounced. Direct colonial rule was rare, but the question of long-lasting indirect impacts on local communities remains unanswered. Indirect effects of colonialism is addressed recently to discuss the impact on the indigenous societies in the periphery of colonial control (Trabert 2017). Taiwan was colonized by the Spanish and the Dutch during the early 17th century, where Northeastern Taiwan is an especially unique example for discussing indirect effects due to its physically isolated location that made it not easily accessible to the Europeans that the colonial control was less compared to other parts of this region (Andrade 2007; Kang 2012). In addition, prior to the European contact, there were small-scale regional exchange networks between China and Taiwan. Also, northern Taiwan had been involved in long-distance networks of East Asia since 14th century, and encountered a large wave of Han Chinese migration in the 19th century. This made northeastern Taiwan a good case to explore culture contacts at different periods and their indirect impacts by taking a long-term perspective. 


We ask whether colonial influence on indigenous populations can be detected in ornaments recovered from the archaeological record at Kiwulan (1400-1900 AD), a large Iron Age settlement in northeastern Taiwan.  Our hypothesis is that there was a greater diversity of ornaments types and materials at Kiwulan after European contact. We hypothesise that after Chinese contact there was a decline in the production, use and discard of ornaments at Kiwulan. We hypothesise that there is no change in the spatial distribution of ornaments at Kiwulan relating to these international contacts. 


Cultural context of Ornaments in Northeastern Taiwan


Historical records from Spanish and Dutch provide rich information about the historical and cultural background both for Europeans and indigenous people in the early 17th century. Spanish occupied and built forts in Northern Taiwan since 1624, from which Spanish missionaries often went to indigenous settlement and left behind numerous records from those places. The report of the Dominican Jacinto Esquivel in 1632 mentioned that the Taparri, an indigenous tribe from northern Taiwan, usually used cuentas (agate beads) as a materials to exchange with necessities they need with other indigenous people. This trend then gradually spread to other areas, and even the Spanish soldiers used agate as bargaining chips for gambling, since agate equaled money (Li 2006: 132-149).  European contact was focused on trading with indigenous communities in northeastern Taiwan. Trading activity of many types of goode among these indigenous communities increased with the arrival of European colonisers. Thus, we predict that this trading activity resulted in an increase in the amount and diversity of ornaments coming into indigenous communities in northeastern Taiwan.
Father Jacinto Esquivel recorded how people in Tamsui entered marriages. A man who wanted to take a wife had to give her parents cuentas. If a married man was found having cheated on his wife, he only had to pay the witness with agate or golden beads and the matter was settled (Li 2006: 151). Other records mention that the female shamans (majuorbol) in the tribe used agate beads for healing ceremonies in rituals (Pao 2008: 122, 143, 151). Regarding funerals, some indigenous people buried the dead under their houses or in the vicinity. They put a mat into the grave to protect the body from moisture and then put cooked rice on both sides of the head as provision. The deceased were buried in small graves with both knees bent, and on the grave they placed quivers with arrows, pottery, agate beads and other things that they would need. The greater the influence of the deceased, the more agate, pottery and cloths were placed on the grave (Li 2006: 153). 
Documents from the Qing dynasty usually describe the decorative purposes of the ornaments. In the Kavalan Subprefecture Gazetteer (Chen 2006[1852]: 308), the Kavalan Zhi Lue (Ko 1993[1837]: 11, 126) and the Dong Cha Ji Lue (Yao 1996[1829]: 77), it is mentioned that aborigines in Yilan used metal threads to weave so called golden carp-shaped ornaments. Their number was small and their value high, hence only the rich possessed them. Ordinary people wore agate beads or glass beads on their head or neck during various festivals. In 1895, at the beginning of Japanese rule over Taiwan, Ino Kanori (Kanori 1996: 227-232) made field surveys among various ethnic groups in Taiwan. He describes the Plains Aborigines from Yilan as not using carp-shaped ornaments any more, but mentions that older people still use beads ornaments.
Recent ethnographic research of the Kavalan tribe describes agate beads as used in divination ceremonies, the subli, by female shamans (Liu 2008: 133-134). Interview records describe agate beads as valuable objects passed down from mother to daughter. When they were not used, they were often put on roof beams so that they were not seen by other people. But the origin of these beads is still not known. Later, because they were bought by Japanese and people in Taipei, agate beads became rarer and rarer (Hsu 1992: 22) and carp-shaped ornaments had completely disappeared. Modern ethnographic research shows that agate beads were not only used as decoration, but also played an important role in divination. It was usually the female shamans that were responsible for divination rites, a technique passed down by ancestors. Most aborigines today don’t know the origin of agate beads any more, but their worth is still highlighted by oral history and through their scarcity. 


Those historical documents from the early 17th century to the modern ethnography described how local indigenous people use those ornaments in local cultural contexts that represents some social roles or status. However, compared to European contact period, there is less mention of beads in Chinese contact period and the description about ornaments is only limited to their dressing culture.   


Kiwulan
Kiwulan (Figure 1) is located at Yilan, north of Lanyang Plain in northeastern Taiwan, surrounded by the Central Mountain Range in the west and the Pacific Ocean in the east. Kiwulan was excavated from 2001 to 2004, and the total excavation area was 3,814 m2. Most beads were found during the excavation and some of them through screens with 20 mm and 1.5 mm mesh. The archaeological evidence includes a rich amount of artifacts, burials, middens, post holes, wooden pillars, and stone structures. The chronology of Kiwulan can be divided into Lower Layer Culture (700 - 1200 AD) and Upper Layer Culture (1400 - 1900 AD) with a sterile layer in between based on a series of 32 radiocarbon dates[a], which coordinate to the late Iron Age and Proto-historical period in Taiwan. This paper focuses on the Upper Layer Culture which overlaps with the contact periods with the Europeans and Chinese. It provides a good examples to discuss the foreign impacts on local indigenous society through body ornaments that usually convey social and cultural meaning by displaying.    
The earliest record of direct European contact with indigenous people in Yilan can be traced back to 1632, when the local settlements were attacked by the Spanish according to the official documents (add citation; Borao Mateo 2009). Later in 1647, the Dutch attacked the indigenous villages in Yilan and forced them to accept colonial rules and economic demands by paying annual tribute (add citation; Borao Mateo 2009). According to Dutch census reports in 1650, Kiwulan was the biggest indigenous community in the Yilan Plain, with a population of 840 adults (Chen 2007; Kang 2012; Li 2014). The diagnostic artifacts during European contact found at Kiwulan including An-ping jars and glass beads that were largely introduced to Taiwan during the early 17th century. 
The European colonization ended in 1662 when they were defeated by the kingdom of Tungning found by Koxinga from China. Later in 1683, the Qing dynasty ruled over Taiwan and a large wave of Han Chinese migrated to Yilan during the late 18th century. The evidence of Chinese migration can be identified from Chinese official records [b]and large amount of Chinese blue-and-white porcelain found at Kiwulan.[c]
The ornaments sampled in this study come from 40 adjacent 4m x 4m units out of 262 units in total since those sampled units were less disturbed by modern constructions and remains intact. The Upper Layer Culture can be divided into six sub layers spanning from 14 century to 19 century according to current radiocarbon dates, excavation depth, types of ceramics, and sediment texture and color (Hsieh 2008; Wang 2011). Layers are assigned numbers from 1 to 6 for which L1 corresponds to the upper context and L6, also the bottom layer, refers to lower context. Based on Hsieh’s (2008) chronological study of Chinese porcelains, L5 and L6 represent pre-European contact period, L4 was the time of European contact, and L2 and L1 was the period of Chinese contact. 
In general, intact ornaments with clear context were mostly found in burials that helps to understand how people wear them and any relationships between shapes of ornaments and gender or age. In addition to burials, ornaments were also found in middens and living space that can be identified by post holes. The frequency of ornaments from burials is more than those from the living space due to well preserved condition. There is a wide variety of raw materials for ornaments  (Table 1) of which ornaments glass, agate and metal ornaments that account for 99% of all ornaments were thought to be introduced by trading with the Europeans and Chinese traders, while ornaments made of shells, woods, and bones were believed locally made that is about only about 1% of all ornaments. The reason for the large quantity of glass beads is that they usually have been found in clusters because of the original form such as necklaces. The shape of ornaments include beads, bracelets, rings, bells, pendants, and knitted objects that shows shape are closely related to raw material due to its characteristic. For example, beads are only made of glass, agate, and shell, and bone is the main material for knitted objects that used to connect beads. Also, metal ornaments covers more shapes such bells, pendants, and rings  (Chen 2007). 


Results


chronological distribution
* Compare the three analytical units 


spatial distribution
* Compare spatial distribution of ornaments three analytical units  






Discussion and Conclusion 
European contact






Chinese contact
















________________


Notes on drafting 


What is the hypothesis?
1. Ornaments in the archaeological record at Kiwulan indicate cultural changes after European contact 
2. Ornaments in the archaeological record at Kiwulan also indicate cultural change after Chinese contact


Background:  


some debate about origins of social inequality in Taiwan… KWL as a important case study… centre of the debates…






H1
   1. We compare ornaments UCL-Pre-E and LCL
   2. Raw material, shape/type, spatial distribution, chronological distribution
H2
   1. We compare ornaments UCL-Pre-E and UCL-Post-E
   2. Raw material, shape/type, spatial distribution, chronological distribution
Results


Discussion and conclusion: 


* Social values, gender, burials


Relevant papers to cite


https://www.tandfonline.com.sci-hub.tw/doi/full/10.1080/0734578X.2018.1471655?scroll=top&needAccess=true


________________


A Research of the Imported Ornaments Excavated from the Kiwulan site, I-lan
Introduction
Culture contact is a big issue which explores the interaction and relationship between two groups from different cultural contexts. In archaeology, the culture contact between European and indigenous people in the postcolonial period is the common studies which explore the roles of European and indigenous people, and how indigenous people understood and reacted to the dynamic processes of colonization (Decorse 1992; Given 2004; Lyons and Papadopoulos 2002; Torrence and Clarke 2000). Despite Taiwan was colonized by Europeans, the Dutch and Spanish, from 1624 to 1662 (Israel 1989: 173-174), little has been discovered in archaeology about the interaction between indigenous groups and Europeans, and how indigenous people reacted in the postcolonial period. 
In addition to historical documents, European materials or the imported materials which are associated with exchange network stimulated by Europeans provide important evidence for understanding the effects of culture contact. One of the common imported artifacts excavated from the late Iron Age (1000-400BP) sites to historical period (400-100BP) in Taiwan are glass beads and agate beads, in which most are imported materials which might enter Taiwan through trade network. Ornaments are usually viewed as materials which convey social meaning in a culture because their function as decoration. Researches about ornaments in this period can be divided into two categories: The first is concern about the technology of beads and another one is interested in the regional exchange system (Chen 2008, Hong 2005, Wang and Liu 2007, Liu 2005). However, these studies tend to view imported materials as an evidence of diffusion of cultural traits and focus on their sourcing and regional circulation. The issues such as how do indigenous people view these imported materials and what is the meaning of imported materials in local settlements are seldom explored. 
In this paper, I will explore the relationship between Europeans and indigenous people by examining the imported materials from late Iron Age Site in Northeastern Taiwan. The Upper Culture Layer (600-100BP) of the Kiwulan site in I-lan was excavated abundant imported materials, including glass beads, agate beads, and metal ornaments, which indicates the trade network stimulated by the Europeans. This article examines historical records and the archaeological contexts in order to know functions of imported ornaments, and their differences and universalities in various subgroups through quantitative analysis and ethnographic records. The aim is to identify the principles of ornaments usage in the Kiwulan society, explore their core social culture through the construction of a value system of various ornaments, and suggest that the ubiquitous ornaments might reflect the results of negotiation between European and indigenous people.
Historical and Ethnographic Background 
Historical records from Spanish and Dutch provide rich information about the historical and cultural background both for Europeans and indigenous people in the early 17th century. Here I focus on how were imported ornaments exchanged between different groups of people, and what is the meaning for those ornaments in local settlements by examining the written records from the observations of Europeans. Spanish occupied and built forts in Northern Taiwan since 1624, from which Spanish missionaries often went to indigenous settlement and left behind numerous records from those places. The report of the Dominican Jacinto Esquivel in 1632 mentioned that the Taparri, an indigenous tribe from northern Taiwan, usually used cuentas (agate beads) as a materials from exchange the necessities they need with other indigenous people. This shows that agate beads were kind of medium of exchange in the trade network. This trend then gradually spread to other areas, and even the Spanish soldiers used agate as bargaining chips for gambling, since agate equaled money (Li 2006: 132-149).
Father Jacinto Esquivel recorded how people in Tamsui entered marriages. A man who wanted to take a wife had to give her parents cuentas. If a married man was found having cheated on his wife, he only had to pay the witness with agate or golden beads and the matter was settled (Li 2006: 151). Other records mention that the female shamans (majuorbol) in the tribe used agate beads for healing ceremonies in rituals (Pao 2008: 122, 143, 151). Regarding funerals, some indigenous people buried the dead under their houses or in the vicinity. They put a mat into the grave to protect the body from moisture and then put cooked rice on both sides of the head as provision. The deceased were buried in small graves with both knees bent, and on the grave they placed quivers with arrows, pottery, agate beads and other things that they would need. The greater the influence of the deceased, the more agate, pottery and cloths were placed on the grave (Li 2006: 153). 
We can see from the literature that agate beads had a certain value; they were used as medium of exchange, as dowry and as payment for settling problems. At the same time they played an important role in healing rites and as grave goods, being an indicator for reputation or a high position. 
Documents from the Qing dynasty usually describe the decorative purposes of the ornaments. In the Kavalan Subprefecture Gazetteer (Chen 2006[1852]: 308), the Kavalan Zhi Lue (Ko 1993[1837]: 11, 126) and the Dong Cha Ji Lue (Yao 1996[1829]: 77), it is mentioned that aborigines in I-lan used metal threads to weave so called golden carp-shaped ornaments. Their number was small and their value high, hence only the rich possessed them. Ordinary people wore agate beads or glass beads on their head or neck during various festivals. Women unearthed from the burials of the Ki-Wu-Lan site did possess more agate beads and glass beads than men, which are verified by documents and records. At the same time, fish-shape ornaments were also unearthed at the site. But, due to the poor condition of the burials, no inferences can be made regarding gender and age of bodies that were given fish-shape ornaments as burial objects. However, from the fact that bodies found with fish-shape ornaments also had comparatively more other grave goods, one can conclude that they were of high value. 
In 1895, at the beginning of Japanese rule over Taiwan, Ino Kanori (Kanori 1996: 227-232) made field surveys among various ethnic groups in Taiwan. He describes the Plains Aborigines from I-lan as not using carp-shaped ornaments any more, but mentions that older people still use beads ornaments.
Recent ethnographic research of the Kavalan tribe describes agate beads as used in divination ceremonies, the subli, by female shamans (Liu 2008: 133-134). Interview records describe agate beads as valuable objects passed down from mother to daughter. When they were not used, they were often put on roof beams so that they were not seen by other people. But the origin of these beads is still not known. Later, because they were bought by Japanese and people in Taipei, agate beads became rarer and rarer (Hsu 1992: 22) and carp-shaped ornaments had completely disappeared. Modern ethnographic research shows that agate beads were not only used as decoration, but also played an important role in divination. It was usually the female shamans that were responsible for divination rites, a technique passed down by ancestors. Most aborigines today don’t know the origin of agate beads any more, but their worth is still highlighted by oral history and through their scarcity. 
Agate beads, glass beads and copper bracelets were not only an ornament for decoration, but also possessed social significance. In the 17th century agate beads were used as currency, as a medium of exchange and were used in rites. In the 19th century they were used as decoration and tribes now usually perceive them as objects for rites and divination. They have become ever scarcer and their origin is already forgotten by aborigines today. We can see that their nature as object of divination has not changed since the 17th century, and even future generations will remember that they were used by female shamans. Previous literature mentions golden beads and agate beads as divination beads of the Kavalan tribe, and both were often worn as ornaments. What value and significance did they actually have, and did they have any relationship? Did the indigenous people accept those different kind of imported ornaments in the same way or treat them separately? Those questions could be answered by examining the archaeological evidence, which shows that different kind of ornaments, such as golden beads and agate beads might have totally different meaning and they are incorporated into indigenous societies based on some existing principles or social rules in their culture.
Archaeological Background 
Kiwulan site in northeastern Taiwan provides a good framework for understanding the interaction between Europeans and indigenous people. The Kiwulan site (Figure 1) is located at I-lan, north of Lanyang Plain in northeastern Taiwan, surrounded by the Central Mountain Range in the west and the Pacific Ocean in the east. Kiwulan site was excavated from 2001 to 2004, and the total excavation area was 3,814 m2. The time period of Kiwulan site can be divided into Lower Layer Culture (1300-800BP) and Upper Layer Culture (600-100BP) based on a series of 32 radiocarbon dates, which coordinate to the Iron Age and Proto-historical period in Taiwan. The archaeological evidence includes a rich amount of artifacts, burials, ash pits, wooden pillars and stone piles. The AD district is the area which has been unearthed most of the artifacts and remains (Figure 2). Preliminary investigation suggests that the wooden pillars were part of a building structure of a main living place. The highest concentration of remains in the Upper Culture Layer indicates a large living space that was used over a long time (Chen et al., 2007, Chiu 2004: 30).
  

Figure 1: Location of the Kiwulan site




 AD區 

Figure 2: The distribution of archaeological remains in AD district








Ornaments found in Kiwulan site
The total number of ornaments found at the Ki-Wu-Lan site amounts to 12,597[1]. They are made of agate, glass, metal, shells, wood and bones (Table 1) and the categories includes beads, rings, bells, pieces and knitted objects. Most of the ornaments come from the Upper Culture Layer and just few found from Lower Culture Layer.
  
 
Figure 1: Frequency of different ornaments






Most ornaments are glass beads, followed by metal ornaments and agate beads, together accounting for 99% of all ornaments. Ornaments made of shell, wood or bone only account for 1% of all ornaments. The reason for the high quantity of glass beads is that they usually have been found in clusters because of their original form, for example, necklaces. 
    The frequency of ornaments from burials is more than those from the living space. There is a total of 125 burials at the Ki-Wu-Lan site, 90 burials belong to the Upper Culture Layer and 35 from the Lower Culture Layer. Burial goods include potteries, stonewares, imported ceramics, metal bracelets, glass beads, wooden combs, coins and bone artifacts. Among the ornaments, metal bracelets and beads have often been found in burial as grave goods (Chen, 2007). 


Ornaments from Iron Age
Research about ornaments from the Iron Age in Taiwan can be roughly divided into two research areas: The first is concerned about the production system of artifacts and the regional interaction system. A component analysis of part of the glass beads from the Ki-Wu-Lan site has been carried out. With Lead Isotope Analysis, Chen (2008) found out that the composition of golden beads among them is similar to lead ore produced in mainland China. The production of agate and metal ornaments from the Ki-Wu-Lan site has not yet been discovered, but initial research suggests that most of the ornaments were foreign. Wang and Liu’s (2007) study of imported materials point out that the 16th and 17th century trade with Spaniards and Dutch was very different from the comparatively inter-insular trade in the prehistoric period. These imported materials after circulating for a long period of time in Taiwan have become important part of the indigenous material culture. 
Regarding the regional interaction system, Hong (2005: 81-940) examines the development of external beads from the Philippine Archipelago and makes inferences about the changing patterns of glass beads excavated in Taiwan. Hong believes that both areas developed from nephrite beads to Indo-Pacific beads and eventually to Chinese coil beads, and suggests that the trade on the South China Sea between Taiwan, Philippines and Southeast Asia can be traced back to the Neolithic Age and becoming more developed and complex during the Iron Age. As for the transfer and changes of domestic and external materials on the island of Taiwan, Liu (2005:211) points out that the appearance of small numbers of imported materials like metal, glass or agate has began from the late period of Neolithic Age (3000-1800BP). The diffusion of the use of metal tools was from north to south on the east coast, with agate and glass beads gradually replacing jade burial objects from 1800 years ago. This process of replacement of decoration system is related with the foreign exchange system. At the end of the prehistoric period, the long-distance trade with Asia area such as India, the Indochina Peninsula and China was incorporated into a world trading system by European expansion in the 16th to 17th century. 
The second research area approaches the excavation of ornaments from a social cultural point of view. People in traditional societies rarely decorate their bodies solely for aesthetic purposes; most ornaments possess religious, economic or political significance and indicate a certain social behavior. From an archeological perspective these artifacts are scarce but of great importance (Lien 2003: 161). Ornaments are an important part of in an ancient society; hence archaeological excavations of ornaments can help to understand their social meaning. This kind of research is concerned about the significance of imported materials in the context of a certain site and the role these materials played in the society. Hong (2005: 94) notes that every single glass bead has to be understood in the context of its excavation site and analyzed with other non-perishable materials such as imported ceramics, iron, gold or coins to clarify the socio economic changes that the beads reflect in a particular community. 
When imported materials enter the local community they can experience a change in meaning. There has been a long period of development in anthropology about the meaning transformation of imported materials. Chen (2004: 63) discusses the production of traditional ceremonial dresses of the Nanwang Puyuma tribe, and describes the development of the traditional “weave” and the later “embroidery”. He believes that although the skill of “embroidery” was imported, it still became indigenous craft that ancestors passed down through re-contextualization. Dresses and personal adornments that originally did not possess any ceremonial value or taboo meaning were given traditional significance in order to conform to the original cultural identity that existed in the society among different ages or genders. This concept of transformation of significance can also be used for archaeological data. Hu (2007) examines glass beads of the Austronesian society of different areas of Taiwan and considers cultural value and change of significance through their material characteristics and fluctuations. Hu points out that different areas exhibit a different logic of usage towards imported material, and the value and significance of materials is continually constructed and reconstructed. 
Ornaments are a part of material culture and through observation and interpretation of the material it becomes possible for archaeologists to interpret the past. From this perspective Hsu (1992) studies glass beads of the Paiwan tribe. On the basis of structural principles, material combinations and legends of the beads, she discusses the underlying social organization. Hsu believes that if we see ornaments only as objects for decorative purposes, we only see their functional significance. But if we consider the ideas and values that people attached to them, we can understand their real significance. Deetz (1977) thinks, especially in regard to historical archaeology, that material culture is not culture but a product of culture. This culture refers to social norms and patterns of thinking and behavior. Miller’s (1987) consumer theory further stresses the independence of the object itself and the close connection of social culture and individuals. He examines the relationship between society and material and believes that the material is a strong manifestation of culture. These objects not only reflect personal tastes and practical characteristics, but at the same time moral standards and social concepts. However, Douglas and Asherwood (1996) point out that the significance of materials is closely related to social practices, symbolizing potential social distinctions and shaping of social classes. For those ornaments that possess less practical value, the examination of materials highlights the close relationship between the object itself and the social culture.
Research Methods
This research conducted a quantitative analysis of ornaments and compared the ornaments from different archaeological contexts such as settlement area and the burials. In burials, the relationships between the ornaments and gender or age will be examined. The temporal changes of the ornaments in different archaeological contexts will also be studies in this research.
The Upper Cultural Layer of the Ki-Wu-Lan site is belongs to the Iron Age in Taiwan (2000-400BP), but because of the Age of Discovery from the 16th century, it actually entered the historical ages, leaving behind a number of foreign descriptions and writings. Therefore this research takes into account literatures and records from Spain, the Netherlands, China and Japan.
Past research about ornaments solely concentrated on specific objects like glass beads, because the ornaments are well preserved and the materials are still precious and important to aborigines. However, the ornaments excavated at the Ki-Wu-Lan site are numerous (including glass beads, agate and metal objects), well preserved and have research potential. Therefore, I believe that view of all the objects in their entirety will enable a better understanding of the usage and characteristics of ornaments.
Results and Discussion
1. Ornament Shapes and Types
This research applies the already existing ornament classification principles of the archaeological reports of Kiwulan site because their shape classification is more detailed. For quantitative reasons, I combine ornaments made of the same material and analyze them accordingly. The following shapes and types of ornaments were excavated at the site:
1. Agate Beads
A total of 783 pieces were found. Natural carnelian was first grinded and then perforated from both sides, however, the holes are often askew. According to their appearance the ornaments can be divided into eight categories. From these eight groups, hexagonal cylinder beads were most common in the burials, followed by cylindrical beads and big barrel beads.
  
 Figure 2: Number of various agate bead shapes


1. Glass Beads
A total of 10,821 pieces were found. The beads from the Upper Culture Layer can be divided into 39 categories (UL1-UL39). Category 1(UL1), golden bead category, was most common (898 pieces), followed by category 7 (UL7), the orange cylindrical bead category (573 pieces) and category 20 (UL20), the red opaque small bead category (88 pieces). All other categories have less than 50 pieces. Golden beads and orange cylindrical beads were the most common categories in the burials.
1. Metal Ornaments
A total of 930 pieces were found. Metal ornaments show a wide range of shapes, are mostly made of copper, but there were iron, gold and silver materials as well. They can be divided into various shapes such as bells, rings or pieces. Metal rings are most common, accounting for 66.8% of all metal ornaments. Metal fish-shape knits were only found in burials (M003 and M011) but not in the settlement area. Small-sized bells were most common in burials, large-sized bells most common in the settlement area. In general, metal rings were the ornaments most commonly found, and they can be subdivided into bracelets and ear rings. 
  

Figure 3: Number of various metal ornament shapes
1. Shell, wooden, and bone ornaments
Shell ornaments are scarce, only one piece of earring was excavated from the Upper Culture Layer and none were found in the burials. Four of the 16 perforated bone and horn ornaments were excavated from M020 and one from M094 (both Upper Culture Layer). The shapes of the objects found in the burials are short and small and don’t show any carvings. We speculate that they were used together with beads.
2. Settlement Area
As part of the area was destroyed by the engineering project, quantitative analysis was only carried out in areas that were well preserved. I used Hsieh (2008: 16) as reference, and divided the Upper Culture Layer into six layers according to her area sampling standard and layer classification principle[2]. Statistical analysis was done on 25 test pits in the AD district (Figure 2); each pit size was 4m x 4m meters, with an accumulated size of 400 square meters. 
  
 未命名.jpg 

Figure 3: Sampling area of AD district
From the overall number of ornaments one can see that their number peaked at L4 and then started to decrease, showing a unimodal distribution (Table 4). At a closer look at the different types of ornaments, I combined ornaments made of similar materials and categorized them into metal ornaments, glass beads, golden beads and agate beads. 
The results show that golden beads start to appear in large numbers in L5, more than other ornaments, reaching a peak at L4 and then descending up to L2. The tendency of glass beads and metal ornaments is similar. These three types are most numerous in L4 and then begin to descend. Only agate beads show a slightly different tendency with a peak in L3.


  

Figure 4: Number of ornaments and distribution in sampling area 
(with L6 the earliest layer and L1 the latest)
  

Figure 5: Distribution of four ornaments in sampling area
(with L6 as the earliest layer and L1 the latest)


3. Quantitative Analysis[3]
1. Method
Objects of the quantitative analysis are glass beads, agate beads and metal ornaments from burials of the Upper Culture Layer. The purpose is to examine whether there are differences between age groups and gender, hence only samples where gender and age could be determined were taken. This research applied the chi-squared test and the Mann-Whitney test from non-parametric statistics. The chi-square test was carried out for the qualitative analysis, mainly to test the relation between the two variables in order to examine the relation of ornaments with gender and age. The Mann-Whitney test was carried out for the quantitative analysis and used for the examination of inter-gender differences in regard to the number of ornaments.
15 male bodies and 19 female bodies were excavated from the burials. First, the chi-square test examines if gender shows a significant relation with specific ornaments. In the case that both men and women have ornaments, from the number of ornaments we can infer if there are any differences. From 61 bodies the age could be determined, and there are six age distribution: two infants (0-1 years), 12 children (3-12 years), two adolescents (12-20 years), 10 adults (20-35), seven middle-aged (35-50) and 2 elderly (over 50 years). In addition, 18 of the bodies were over 18.
There are problems of samples from age groups being too small, therefore percentage observation could be an additional explanation, and I also combined the infants, children and adolescents into a group (pre-adult group) and the adults, middle-aged and elderly into a group (adult group). Now the pre-adult group consists of 16 samples and the adult group of 37 samples.


1. SPSS results
The results suggest that the external ornaments excavated from the Ki-Wu-Lan site possess the following distribution characteristics:
(1) Gender shows a significant difference of ornaments, however age group does not have a significant difference, and only the percentage shows a difference in proportion.
(2) Regarding gender, most of the agate beads were found with female bodies, only one male body was found with agate beads[4], indicating that they were burial objects only given to women. Glass beads appear to be also given primarily to women. Metal rings were found with both men and women, however the number found with women was greater than men. For earrings and golden beads we could not find any significant gender-related difference.
(3) Wide metal rings were found with adults and all adolescents, suggesting a relationship between thick metal bracelet and adolescents. Bells were found with each body between 6 and eleven years, showing that they were a burial object for children.
(4) Regarding their possessions of ornaments and their number of possessions, adults and pre-adults don’t show any differences, suggesting that there was no distinction between adults and pre-adults.
Conclusion
The following features can be summarized to explain the characteristics of the ornaments found at Kiwulan site:
 
1. Most ornaments were excavated from the settlement area but also burials; however, the ornaments from the burials were more elaborate. Metal weavings in fish-shape were only excavated from two burials out of 90 burials of the Upper Culture Layer. According to historical literatures, these metal weavings were called “golden carp-shape” ornament, which is valuable in their society. The most common ornaments found in the burials are metal rings, excavated from 66 of 90 burials.
2. The distribution of golden beads, glass beads and metal ornaments in the different layers is similar, all of them peaking at L4. Golden beads, however, are most numerous. Agate beads differ from the distribution of the three aforementioned ornaments. They are less numerous and their number increases when the number of other ornaments decreases, indicating a possible different origin.
3. Initial statistical analysis suggests that agate beads were burial objects for women. The usage of metal rings and glass beads is similar among the whole population. But women possessed more metal rings and glass beads than men. Adolescents wore wide metal rings, and children, bells.
   Archaeological data show that agate beads given as burial objects show a gender difference. Agate beads seem to have a special meaning for women and modern ethnographic records suggest that they were used by the Kavalan people for divination, which was usually practiced by women. Spanish literature describes agate beads as medium of exchange and dowry. Some ethnographic records show that golden beads were used as an object for divination. But their meaning was very different which can be explained with the archaeological evidence. The universality of golden beads found in burials may be related to an influx in large numbers during that period or to the preference of the residents for these beads. They were easy to obtain, very popular in this area and more numerous than agate beads. When other ornaments prevailed, the number of agate beads declined, but they were still used as grave goods. The agate beads found were small in number, but still they were used as burial objects. Compared to golden beads, they might indicate a higher rank, and the fact that they were only found with women indicates their uniqueness in the society.
  The ornaments found at Ki-Wu-Lan society indicate different values and patterns of usage based on the burials and living area data. This reveals that the ornaments were not only used as decoration, they were items that carried cultural significance, which also means Kiwulan people transformed the meaning the imported material, and then recontextualize them into local materials by daily usage and ritual practice. In addition, the abundance of ornaments present the preference of local people and the interaction and negotiation between Kiwulan people and European or Chinese traders. The exchange of beads seems based on the pre-existing principles of exchange, which shows the agency of local indigenous people.        


________________
[1] This number contains ornaments from the Upper Culture Layer, Lower Culture Layer, soil layer, old riverbed stratified deposit, surface collection and disrupted layer. 
[2] The elevation of the Upper Culture Layer is between -80 and 110 centimeters, Hsieh divided it into six major layers according to the contents of the cultural layer with cross-pit burial data. 
[3] The α value is set at 0.1 in SPSS.
[4] We assume that the M108 is a male burial, but because of the poor condition of the bones we cannot confirm this assumption. 
[a]put these in a table here
[b]citation
[c]citation
