---
title: "Title Goes Here"
author:
  - Author One
  - Author Two
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
    bookdown::html_document2:
      fig_caption: yes
      reference_docx: "../templates/template.docx" # Insert path for the DOCX file
bibliography: references.bib
csl: "../templates/journal-of-archaeological-science.csl" # Insert path for the bib-style
abstract: |
  Text of abstract
keywords: |
  keyword 1; keyword 2; keyword 3
highlights: |
  These are the highlights. 
---


<!-- This is the format for text comments that will be ignored during renderings. Do not put R code in these comments because it will not be ignored. -->

```{r, setup, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  echo = FALSE,
  comment = "#>",
  fig.path = "../figures/"
)

```

# Introduction

Here is a citation [@Marwick2017]

# Background

```{r read-in-the-data, eval = FALSE}
library(here)
kwl_upper <- readxl::read_excel(here("analysis", "data", "raw_data", "Kiwulan_Ornament_Upper.xlsx"))
```

# Methods

# Results

```{r tidy-data, eval = FALSE}
# summarise the ornaments by layers
library(tidyverse)
library(ggplot2)

# L5 and L6 represent pre-European contact period, 
# L4 was the time of European contact, and 
# L2 and L1 was the period of Chinese contact. 

ornaments_period <- 
kwl_upper %>% 
  filter(!is.na(`6-layers`)) %>% 
  mutate(period = case_when(
    `6-layers` %in% 1:2 ~ "Chinese Contact",
    `6-layers` == 4 ~ "European Contact",
    `6-layers` %in% 5:6 ~ "Before European Contact",
     TRUE ~ "other"
  )) %>% 
  filter(period != "other") %>% 
  mutate(period = factor(period,
                       level = c("Before European Contact", 
                                                "European Contact", 
                                                "Chinese Contact"))) %>% 
  mutate(Length = as.numeric(`Length(mm)`),
         Thick = as.numeric(`Thick(mm)`),
         Width = as.numeric(`Width(mm)`),
         Perforation1 = as.numeric(`Perforation1(mm)`)) %>% 
  rowwise() %>% 
  mutate(Perforation_average = mean(c(`Perforation1`, `Perforation2(mm)`), 
                               na.rm = TRUE))
```


```{r plot-counts}
# need to reorder, try https://forcats.tidyverse.org/reference/index.html
# reorder factor for categories (by frequency) and period (manually)
# total number of ornaments for each categories 

ornaments_count_test <-
  ornaments_period %>% 
  filter(!is.na(`6-layers`),
         Categories != "Unknown Metal") %>% 
  mutate(Categories = as.factor(Categories)) %>% 
  mutate(Categories = fct_lump(Categories, 
                               n = 5)) %>% 
  group_by(Categories) %>%
  count() %>% 
  ungroup() %>% 
  mutate(Categories = fct_reorder(Categories, n))

ggplot(ornaments_count_test,
       aes(Categories, n)) +
  geom_col() +
  coord_flip() +
  labs(y = "Frequency",
       x = "Categories") +
  theme_minimal(base_size = 14)
```


```{r plot-counts-by-period}
# categories of ornaments by period
ornaments_count <-
  ornaments_period %>% 
  filter(!is.na(`6-layers`),
         Categories != "Unknown Metal") %>% 
  mutate(Categories = fct_lump(Categories, 
                               n = 5)) %>% 
  mutate(Categories = fct_infreq(Categories)) %>% 
  mutate(Categories = fct_rev(Categories)) %>% 
  group_by(period, Categories) %>%
  count() %>% 
  ungroup() 

ggplot(ornaments_count) +
  geom_col(aes(Categories, n)) +
  facet_wrap(~ period) +
  coord_flip() +
  labs(y = "Frequency",
       x = "Categories") +
  theme_minimal(base_size = 14)
```

```{r scatter-plot-bead-by-period}
# plot for intact golden bead by period
ornaments_intact_gold <-
  ornaments_period %>% 
  filter(Condition %in% c('complete', 'near-complete'),
         Categories == 'Golden bead')
  
ggplot(ornaments_intact_gold) +
  geom_point(aes(Length, Width, col = Perforation_average)) +
  facet_wrap(~ period) +
  labs(x = "Length (mm)",
       y = "Width (mm)",
       title = "Golden beads") +
  coord_fixed(ratio = 1) +
  theme_minimal() +
  theme(plot.title = element_text(hjust=0.5))

# plot for intact glass bead by period
# need to deal with the original data

# plot for intact agate bead by period
ornaments_intact_agate <-
  ornaments_period %>% 
  filter(Condition %in% c('complete','near-complete'),
         Categories == 'Agate bead')
  
ggplot(ornaments_intact_agate, 
       aes(Length, Width, col = period))+
  geom_point() +
  labs(x = "Length (mm)",
       y = "Width (mm)",
       title = "Agate beads") +
  coord_fixed(ratio = 1) +
  theme_minimal() +
  theme(plot.title = element_text(hjust=0.5))
```

```{r plot-count-type-by-period}
# plot for different shape of agate bead by period
agate_bead_shape <-
  ornaments_period %>% 
  filter(Categories == 'Agate bead') %>% 
  mutate(Type = ifelse(Type == 'prism/octagonal', 
                       str_remove(Type, '/octagonal'), Type)) %>% 
  mutate(Type = ifelse(Type == 'prism/pentagonal', 
                       str_remove(Type, '/pentagonal'), Type)) %>% 
  mutate(Type = ifelse(Type == 'prism/hexagonal', 
                       str_remove(Type, 'prism/'), Type)) %>% 
  mutate(Type = fct_infreq(Type)) %>% 
  mutate(Type = fct_rev(Type)) %>% 
  group_by(period, Type) %>% 
  count()

ggplot(agate_bead_shape) +
  geom_col(aes(Type, n)) +
  facet_wrap(~ period) +
  coord_flip() +
  labs(y = "Frequency",
       x = "Shape of Agate bead") +
  theme_minimal(base_size = 14)

# plot for different shape of metal bell by period
bell_shape <-
  ornaments_period %>% 
  filter(Categories == 'Bell',
         Type != 'unclassified') %>% 
  mutate(Type = fct_infreq(Type)) %>% 
  mutate(Type = fct_rev(Type)) %>% 
  group_by(period, Type) %>% 
  count()

ggplot(bell_shape) +
  geom_col(aes(Type, n)) +
  facet_wrap(~ period) +
  coord_flip() +
  labs(y = "Frequency",
       x = "Shape of Bell") +
  theme_minimal(base_size = 14)

# plot for different shape of metal ring by period
ring_shape <-
  ornaments_period %>% 
  filter(Categories == 'Metal ring') %>% 
  mutate(Type = fct_infreq(Type)) %>% 
  mutate(Type = fct_rev(Type)) %>% 
  group_by(period, Type) %>% 
  count()

ggplot(ring_shape) +
  geom_col(aes(Type, n)) +
  facet_wrap(~ period) +
  coord_flip() +
  labs(y = "Frequency",
       x = "Shape of Metal ring") +
  theme_minimal(base_size = 14)
```

```{r scatter-plot-metal-by-period}
# plot for intact bell by period
ornaments_intact_bell <-
  ornaments_period %>% 
  filter(Condition %in% c('complete', 'near-complete'),
         Categories == 'Bell',
         Type != 'unclassified') %>% 
  mutate(Length = as.numeric(gsub("\\+", "", `Length(mm)`))) #remove +
  
ggplot(ornaments_intact_bell) +
  geom_point(aes(Length, Width, col = Type)) +
  facet_wrap(~ period) +
  labs(x = "Length (mm)",
       y = "Width (mm)",
       title = "Bell") +
  coord_fixed(ratio = 1) +
  theme_minimal() +
  theme(plot.title = element_text(hjust=0.5))

# plot for intact ring by period
ornaments_intact_ring <-
  ornaments_period %>% 
  filter(Condition %in% c('complete', 'near-complete'),
         Categories == 'Metal ring') %>% 
  mutate(Length = as.numeric(gsub("\\+|\\-", "", `Length(mm)`))) #remove + -
  
ggplot(ornaments_intact_ring) +
  geom_point(aes(Length, Width, col = Type)) +
  facet_wrap(~ period) +
  labs(x = "Length (mm)",
       y = "Width (mm)",
       title = "Metal ring") +
  theme_minimal() +
  theme(plot.title = element_text(hjust=0.5))
```

```{r read-in-the-spatial-data, eval = FALSE}
library(sf)
library(cartography)
burial <- st_read(here("analysis", "data", "raw_data", "AD_burial.shp"))
AD <- st_read(here("analysis", "data", "raw_data", "AD_zone.shp"))
AD_data <- st_read(here("analysis", "data", "raw_data", "AD_withdata.shp"))
location <- st_read(here("analysis", "data", "raw_data", "location.shp"))
units_40 <- read.csv(here("analysis", "data", "raw_data", "kwl-list-of-sampling-squares.csv"))
```

```{r tidy-data, eval = FALSE}
# 40 sampling units
sample_units <-
  AD_data %>% 
  semi_join(units_40, by = c (`坑號` = "the_sq"))

# join two dataset to get coordinate
ornaments_period_join <-
  ornaments_period %>%
  mutate(period = as.factor(period)) %>% # seems need this line first 
  group_by(Pit_No, period) %>% 
  count(Categories) %>% 
  inner_join(AD_data, by = c("Pit_No" = "坑號"))
```

```{r plot-spatial-distribution}
# filter golden bead
ornaments_period_join_gold <-
  ornaments_period_join %>% 
  filter(Categories %in% 'Golden bead')

# plot by period
ggplot(ornaments_period_join_gold) +
  geom_sf(data = sample_units, fill = NA) +
  geom_sf(data = ornaments_period_join_gold, aes(fill = n), alpha = 0.9) +
  facet_wrap(~ period) +
  labs(title = "Spatial Distribution of Golden Beads",
       fill = "frequency") +
  scale_fill_gradient(high = "black", low = "grey") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        strip.text.x = element_text(size = 11))

# filter glass bead
ornaments_period_join_gold <-
  ornaments_period_join %>% 
  filter(Categories %in% 'Glass bead')

# plot by period
ggplot(ornaments_period_join_gold) +
  geom_sf(data = sample_units, fill = NA) +
  geom_sf(data = ornaments_period_join_gold, aes(fill = n), alpha = 0.9) +
  facet_wrap(~ period) +
  labs(title = "Spatial Distribution of Glass Beads",
       fill = "frequency") +
  scale_fill_gradient(high = "black", low = "grey") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        strip.text.x = element_text(size = 11))

# filter agate bead
ornaments_period_join_gold <-
  ornaments_period_join %>% 
  filter(Categories %in% 'Agate bead')

# plot by period
ggplot(ornaments_period_join_gold) +
  geom_sf(data = sample_units, fill = NA) +
  geom_sf(data = ornaments_period_join_gold, aes(fill = n), alpha = 0.9) +
  facet_wrap(~ period) +
  labs(title = "Spatial Distribution of Agate Beads",
       fill = "frequency") +
  scale_fill_gradient(high = "black", low = "grey") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        strip.text.x = element_text(size = 11))
```

```{r-gganimate}
# test gganimate for measurement of beads by period
devtools::install_github('thomasp85/gganimate')
library(gganimate)

anim_gold_bead <-
  ggplot(ornaments_intact_gold,
       aes(Length, Width)) +
  geom_point() +
  transition_states(period, 3, 1) +
  labs(title = 'Period: {closest_state}',
       x ='Length (mm) of golden bead',
       y ='Width (mm) of golden bead')

# does not work
anim_gold_bead_spatial <-
  ggplot(ornaments_period_join_gold) +
  geom_sf(data = sample_units, fill = NA) +
  geom_sf(data = ornaments_period_join_gold, aes(fill = n), alpha = 0.9) +
  transition_states(period, 3, 1) +
  scale_fill_gradient(high = "black", low = "grey") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        strip.text.x = element_text(size = 11))

```

# Discussion

# Conclusion

# Acknowledgements

<!-- The following line inserts a page break when the output is MS Word. For page breaks in PDF, use \newpage on its own line.  -->
##### pagebreak

# References 
<!-- The following line ensures the references appear here for the MS Word or HTML output files, rather than right at the end of the document (this will not work for PDF files):  -->
<div id="refs"></div>

##### pagebreak

### Colophon

This report was generated on `r Sys.time()` using the following computational environment and dependencies: 

```{r colophon, cache = FALSE}
# which R packages and versions?
devtools::session_info()
```

The current Git commit details are:

```{r}
# what commit is this file at? 
git2r::repository(here::here())
```
